CREATE DEFINER=`admin`@`%` FUNCTION `loginS`(email VARCHAR(45), pass VARCHAR(20)) RETURNS int(11)
BEGIN
DECLARE c INT;
SELECT COUNT(*) INTO c FROM STUDENT
WHERE STU_EMAIL = email AND STU_PASS = pass;

RETURN c;
END