CREATE DEFINER=`admin`@`%` FUNCTION `loginP`(email VARCHAR(45), pass VARCHAR(20)) RETURNS int(11)
BEGIN
DECLARE c INT;
SELECT COUNT(*) INTO c FROM PROFESSOR 
WHERE PROF_EMAIL = email AND PROF_PASS = pass;

RETURN c;
END