CREATE DEFINER=`admin`@`%` PROCEDURE `modifyAttendance`(attendanceid int, stuid int)
BEGIN
DECLARE x int;

SELECT ATT_REC_PRESENT INTO x FROM ATTENDANCE_RECORD WHERE ATTENDANCE_ID = attendanceid AND STU_ID = stuid;

	IF x = 1 THEN
		UPDATE ATTENDANCE_RECORD SET ATT_REC_PRESENT = 0 WHERE ATTENDANCE_ID = attendanceid AND STU_ID = stuid;
	ELSE 
		UPDATE ATTENDANCE_RECORD SET ATT_REC_PRESENT = 1 WHERE ATTENDANCE_ID = attendanceid AND STU_ID = stuid;
	END IF;
END