CREATE DEFINER=`admin`@`%` PROCEDURE `unregister`(stuid int, crn int)
BEGIN
DELETE FROM ENROLLMENT WHERE STUDENT_STU_ID = stuid AND COURSE_COURSE_CRN = crn;
DELETE FROM ATTENDANCE_RECORD WHERE STU_ID = stuid AND COURSE_CRN = crn;
END