CREATE DEFINER=`admin`@`%` PROCEDURE `viewCourseS`(stuid int)
BEGIN
	SELECT c.COURSE_CRN, c.COURSE_CODE, c.COURSE_NAME, p.PROF_LNAME, l.LOCATION_NAME 
	FROM COURSE c
	INNER JOIN PROFESSOR p
		ON c.PROF_ID = p.PROF_ID
	INNER JOIN LOCATION l
		ON c.LOCATION_ID = l.LOCATION_ID
	INNER JOIN ENROLLMENT e
		ON c.COURSE_CRN = e.COURSE_COURSE_CRN
	WHERE e.STUDENT_STU_ID = stuid;
END