CREATE DEFINER=`admin`@`%` PROCEDURE `viewAttendanceP`(att_id int)
BEGIN
	SELECT ATTENDANCE_RECORD.STU_ID, STU_FNAME, STU_LNAME, ATT_REC_PRESENT 
    FROM ATTENDANCE_RECORD
	INNER JOIN STUDENT
		ON STUDENT.STU_ID=ATTENDANCE_RECORD.STU_ID
	WHERE ATTENDANCE_ID=att_id
    ORDER BY STU_LNAME ASC;
END