CREATE DEFINER=`admin`@`%` PROCEDURE `viewAttendanceS`(stuid int, crn int)
BEGIN
	SELECT a.ATTENDANCE_DATETIME, r.ATT_REC_PRESENT FROM ATTENDANCE_RECORD r
    INNER JOIN ATTENDANCE a
    ON a.ATTENDANCE_ID = r.ATTENDANCE_ID
	WHERE r.STU_ID = stuid AND r.COURSE_CRN = crn
	ORDER BY a.ATTENDANCE_DATETIME ASC;
END